name = "termination"
defaultTargets = ["Matrix", "Farkas", "Coverage", "Logic", "Net", "MainTheorem", "Termination"]

[[lean_lib]]
name = "Matrix"

[[lean_lib]]
name = "Farkas"

[[lean_lib]]
name = "Coverage"

[[lean_lib]]
name = "Logic"

[[lean_lib]]
name = "Net"

[[lean_lib]]
name = "MainTheorem"

[[lean_lib]]
name = "Termination"
