from typing import Sequence, overload, override
from .zrth import IType

class Type:
    @property
    def shape(self) -> tuple[int, int]: ...

class Int(Type):
    def __init__(self, i: int, j: int) -> None: ...

class Bool(Type):
    def __init__(self, i: int, j: int) -> None: ...

class Wire:
    def __init__(self, typ: Type) -> None: ...
    @property
    def id(self) -> int: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class TermInterface(Sequence[Wire]):
    def __getitem__(self, index: int) -> Wire: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...

class Term:
    @staticmethod
    def function(itype: IType, write: Sequence[Wire], read: Sequence[Wire]) -> Term: ...
    @staticmethod
    def constant(itype: IType, write: Sequence[Wire]) -> Term: ...
    @overload
    def __init__(self, itype: IType, write: Sequence[Wire]) -> None: ...
    @overload
    def __init__(self, itype: IType, write: Sequence[Wire], read: Sequence[Wire]) -> None: ...
    @property
    def write(self) -> TermInterface: ...
    @property
    def read(self) -> TermInterface: ...
    @property
    def itype(self) -> IType: ...
    @override
    def __repr__(self) -> str: ...

class AtomInterface(Sequence[Wire]):
    def __getitem__(self, index: int) -> Wire: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...

class AtomBlockInterface(Sequence[Wire]):
    def __getitem__(self, index: int) -> Wire: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...

class AtomBlock(Sequence[Term]):
    def __getitem__(self, index: int) -> Term: ...
    def __len__(self) -> int: ...
    def read(self) -> AtomBlockInterface: ...
    def write(self) -> AtomBlockInterface: ...
    @override
    def __repr__(self) -> str: ...

class Atom:
    @property
    def read(self) -> AtomInterface: ...
    @property
    def ctrl(self) -> AtomInterface: ...
    @property
    def wait(self) -> AtomInterface: ...
    @property
    def init(self) -> AtomBlock: ...
    @property
    def update(self) -> AtomBlock: ...
    def __str__(self) -> str: ...
    @override
    def __repr__(self) -> str: ...

class ModuleTermInterface(Sequence[Wire]):
    def __getitem__(self, index: int) -> Wire: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...

class ModuleTerm:
    def read(self) -> ModuleTermInterface: ...
    def write(self) -> ModuleTermInterface: ...
    @override
    def __repr__(self) -> str: ...

class ModuleAtomBlock(Sequence[ModuleTerm]):
    def __getitem__(self, index: int) -> ModuleTerm: ...
    def __len__(self) -> int: ...
    @override
    def __repr__(self) -> str: ...

class ModuleAtom:
    def init(self) -> ModuleAtomBlock: ...
    def update(self) -> ModuleAtomBlock: ...
    @override
    def __repr__(self) -> str: ...

class ModuleAtoms(Sequence[ModuleAtom]):
    def __getitem__(self, index: int) -> ModuleAtom: ...
    def __len__(self) -> int: ...

class Module:
    @staticmethod
    def sequential(
        init: Sequence[Term],
        update: Sequence[Term],
        obs: Sequence[tuple[Wire, Wire]] | None = None,
        *,
        prvt: Sequence[tuple[Wire, Wire]] | None = None,
    ) -> Module: ...
    @staticmethod
    def combinatorial(
        assign: Sequence[Term],
        obs: Sequence[tuple[Wire, Wire]] | None = None,
    ) -> Module: ...
    @staticmethod
    def parallel(*modules: Module) -> Module: ...
    @property
    def atoms(self) -> ModuleAtoms: ...
    def __str__(self) -> str: ...
    @override
    def __repr__(self) -> str: ...
