from torch import Tensor as TorchTensor
from typing import override, Iterable

class Wire:
    def __init__(self, dtype: DType) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def dtype(self) -> DType: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class DType:
    class Bool:
        def __init__(self, shape: list[int]) -> None: ...

    class Int:
        def __init__(self, shape: list[int]) -> None: ...

    class Float:
        def __init__(self, shape: list[int]) -> None: ...

    class Real:
        def __init__(self, shape: list[int]) -> None: ...

    class UWord:
        def __init__(self, width: int) -> None: ...

    class SWord:
        def __init__(self, width: int) -> None: ...

    @staticmethod
    def from_str(s: str) -> DType: ...
    @property
    def shape(self) -> list[int]: ...
    def eq_dtype(self, other: DType) -> bool: ...
    def reshape(self, shape: list[int]) -> DType: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __repr__(self) -> str: ...

class IType:
    @staticmethod
    def Add() -> IType: ...
    @staticmethod
    def Sub() -> IType: ...
    @staticmethod
    def Mul() -> IType: ...
    @staticmethod
    def Div() -> IType: ...
    @staticmethod
    def MatMul() -> IType: ...
    @staticmethod
    def Eq() -> IType: ...
    @staticmethod
    def Neq() -> IType: ...
    @staticmethod
    def Lt() -> IType: ...
    @staticmethod
    def Le() -> IType: ...
    @staticmethod
    def Gt() -> IType: ...
    @staticmethod
    def Ge() -> IType: ...
    @staticmethod
    def And() -> IType: ...
    @staticmethod
    def Or() -> IType: ...
    @staticmethod
    def Not() -> IType: ...
    @staticmethod
    def Ite() -> IType: ...
    @staticmethod
    def Id() -> IType: ...
    @staticmethod
    def Argmax() -> IType: ...
    @staticmethod
    def TensorGet() -> IType: ...
    @staticmethod
    def TensorSet() -> IType: ...
    @staticmethod
    def TensorSum() -> IType: ...
    @staticmethod
    def TensorMean() -> IType: ...
    @staticmethod
    def TensorMax() -> IType: ...
    @staticmethod
    def Linear() -> IType: ...
    @staticmethod
    def Tensor(val: TorchTensor) -> IType: ...

class Term:
    @staticmethod
    def function(itype: IType, write: list[Wire], read: list[Wire]) -> Term: ...
    @staticmethod
    def constant(itype: IType, write: list[Wire]) -> Term: ...
    def __init__(
        self, itype: IType, write: list[Wire], read: list[Wire] | None = None
    ) -> None: ...
    def write(self) -> Iterable[Wire]: ...
    def read(self) -> Iterable[Wire]: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __repr__(self) -> str: ...

class Atom:
    @property
    def init(self) -> Iterable[Term]: ...
    @property
    def update(self) -> Iterable[Term]: ...

class Transition: ...

class Module:
    @property
    def atoms(self) -> Iterable[Atom]: ...
    def sequential(
        init: Iterable[Term],
        update: Iterable[Term],
        obs: None | Iterable[tuple[Wire, Wire]] = None,
        ctrl: None | Iterable[tuple[Wire, Wire]] = None,
        extl: None | Iterable[tuple[Wire, Wire]] = None,
        intf: None | Iterable[tuple[Wire, Wire]] = None,
        prvt: None | Iterable[tuple[Wire, Wire]] = None,
    ) -> Module: ...
    def combinatorial(
        assign: Iterable[Term],
        obs: None | Iterable[tuple[Wire, Wire]] = None,
        extl: None | Iterable[tuple[Wire, Wire]] = None,
        intf: None | Iterable[tuple[Wire, Wire]] = None,
    ) -> Module: ...
    def parallel(*modules: Module) -> Module: ...
    @property
    def intf(self) -> Iterable[tuple[Wire, Wire]]: ...
    @property
    def extl(self) -> Iterable[tuple[Wire, Wire]]: ...
    @property
    def prvt(self) -> Iterable[tuple[Wire, Wire]]: ...
    @property
    def ctrl(self) -> Iterable[tuple[Wire, Wire]]: ...
