from torch import Tensor as TorchTensor
from typing import Iterable, override

class Wire:
    def __init__(self, dtype: DType) -> None: ...
    def id(self) -> int: ...
    @property
    def dtype(self) -> DType: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __hash__(self) -> int: ...

class DType:
    class Bool:
        def __init__(self, shape: list[int]) -> None: ...
        @property
        def shape(self) -> list[int]: ...
        def reshape(self, shape: list[int]) -> "DType.Bool": ...
        def is_bool(self) -> bool: ...
        def is_int(self) -> bool: ...
        def is_float(self) -> bool: ...
        def is_real(self) -> bool: ...
        def is_bv(self) -> bool: ...
        def bv_bw(self) -> int: ...
        def bv_signed(self) -> bool: ...

    class Int:
        def __init__(self, shape: list[int]) -> None: ...
        @property
        def shape(self) -> list[int]: ...
        def reshape(self, shape: list[int]) -> "DType.Int": ...
        def is_bool(self) -> bool: ...
        def is_int(self) -> bool: ...
        def is_float(self) -> bool: ...
        def is_real(self) -> bool: ...
        def is_bv(self) -> bool: ...
        def bv_bw(self) -> int: ...
        def bv_signed(self) -> bool: ...

    class Float:
        def __init__(self, shape: list[int]) -> None: ...
        @property
        def shape(self) -> list[int]: ...
        def reshape(self, shape: list[int]) -> "DType.Float": ...
        def is_bool(self) -> bool: ...
        def is_int(self) -> bool: ...
        def is_float(self) -> bool: ...
        def is_real(self) -> bool: ...
        def is_bv(self) -> bool: ...
        def bv_bw(self) -> int: ...
        def bv_signed(self) -> bool: ...

    class Real:
        def __init__(self, shape: list[int]) -> None: ...
        @property
        def shape(self) -> list[int]: ...
        def reshape(self, shape: list[int]) -> "DType.Real": ...
        def is_bool(self) -> bool: ...
        def is_int(self) -> bool: ...
        def is_float(self) -> bool: ...
        def is_real(self) -> bool: ...
        def is_bv(self) -> bool: ...
        def bv_bw(self) -> int: ...
        def bv_signed(self) -> bool: ...

    class UWord:
        def __init__(self, width: int) -> None: ...
        @property
        def shape(self) -> list[int]: ...
        def is_bool(self) -> bool: ...
        def is_int(self) -> bool: ...
        def is_float(self) -> bool: ...
        def is_real(self) -> bool: ...
        def is_bv(self) -> bool: ...
        def bv_bw(self) -> int: ...
        def bv_signed(self) -> bool: ...

    class SWord:
        def __init__(self, width: int) -> None: ...
        @property
        def shape(self) -> list[int]: ...
        def is_bool(self) -> bool: ...
        def is_int(self) -> bool: ...
        def is_float(self) -> bool: ...
        def is_real(self) -> bool: ...
        def is_bv(self) -> bool: ...
        def bv_bw(self) -> int: ...
        def bv_signed(self) -> bool: ...

    @property
    def shape(self) -> list[int]: ...
    def reshape(self, shape: list[int]) -> "DType": ...
    def is_bool(self) -> bool: ...
    def is_int(self) -> bool: ...
    def is_float(self) -> bool: ...
    def is_real(self) -> bool: ...
    def is_bv(self) -> bool: ...
    def bv_bw(self) -> int: ...
    def bv_signed(self) -> bool: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __repr__(self) -> str: ...

class IType:
    # Arithmetic
    @staticmethod
    def Add() -> "IType": ...
    @staticmethod
    def Sub() -> "IType": ...
    @staticmethod
    def Mul() -> "IType": ...
    @staticmethod
    def Div() -> "IType": ...
    @staticmethod
    def Mod() -> "IType": ...
    @staticmethod
    def Neg() -> "IType": ...
    @staticmethod
    def Abs() -> "IType": ...
    @staticmethod
    def MatMul() -> "IType": ...

    # Comparison
    @staticmethod
    def Eq() -> "IType": ...
    @staticmethod
    def Neq() -> "IType": ...
    @staticmethod
    def Lt() -> "IType": ...
    @staticmethod
    def Le() -> "IType": ...
    @staticmethod
    def Gt() -> "IType": ...
    @staticmethod
    def Ge() -> "IType": ...

    # Logical
    @staticmethod
    def And() -> "IType": ...
    @staticmethod
    def Or() -> "IType": ...
    @staticmethod
    def Not() -> "IType": ...
    @staticmethod
    def Xor() -> "IType": ...
    @staticmethod
    def Xnor() -> "IType": ...
    @staticmethod
    def Implies() -> "IType": ...

    # Control flow
    @staticmethod
    def Ite() -> "IType": ...

    # Transcendental
    @staticmethod
    def Sin() -> "IType": ...
    @staticmethod
    def Cos() -> "IType": ...

    # Special
    @staticmethod
    def Id() -> "IType": ...
    @staticmethod
    def Argmax() -> "IType": ...
    @staticmethod
    def ReLU() -> "IType": ...
    @staticmethod
    def Tanh() -> "IType": ...
    @staticmethod
    def Linear() -> "IType": ...

    # Tensor operations
    @staticmethod
    def TensorGet() -> "IType": ...
    @staticmethod
    def TensorSet() -> "IType": ...
    @staticmethod
    def TensorSum() -> "IType": ...
    @staticmethod
    def TensorMean() -> "IType": ...
    @staticmethod
    def TensorMax() -> "IType": ...

    # Word-level operations
    @staticmethod
    def BitSelect(high: int, low: int) -> "IType": ...
    @staticmethod
    def Extend(width: int) -> "IType": ...
    @staticmethod
    def ToBool() -> "IType": ...
    @staticmethod
    def ToWord1() -> "IType": ...
    @staticmethod
    def ToUnsigned() -> "IType": ...
    @staticmethod
    def ToSigned() -> "IType": ...

    # Constants
    @staticmethod
    def Tensor(val: TorchTensor) -> "IType": ...
    @staticmethod
    def ConstBool(val: bool) -> "IType": ...
    @staticmethod
    def ConstInt(val: int) -> "IType": ...
    @staticmethod
    def Uninterpreted(name: str) -> "IType": ...

    @override
    def __str__(self) -> str: ...
    @override
    def __repr__(self) -> str: ...

class Term:
    @staticmethod
    def function(itype: IType, write: list[Wire], read: list[Wire]) -> "Term": ...
    @staticmethod
    def constant(itype: IType, write: list[Wire]) -> "Term": ...
    def __init__(
        self, itype: IType, write: list[Wire], read: list[Wire] | None = None
    ) -> None: ...
    @property
    def write(self) -> Iterable[Wire]: ...
    @property
    def read(self) -> Iterable[Wire]: ...
    @property
    def itype(self) -> IType: ...
    @override
    def __str__(self) -> str: ...
    @override
    def __repr__(self) -> str: ...

class Atom:
    @property
    def init(self) -> Iterable[Term]: ...
    @property
    def update(self) -> Iterable[Term]: ...

class Module:
    @property
    def atoms(self) -> Iterable[Atom]: ...
    @staticmethod
    def sequential(
        init: Iterable[Term],
        update: Iterable[Term],
        obs: Iterable[tuple[Wire, Wire]] | None = None,
        ctrl: Iterable[tuple[Wire, Wire]] | None = None,
        extl: Iterable[tuple[Wire, Wire]] | None = None,
        intf: Iterable[tuple[Wire, Wire]] | None = None,
        prvt: Iterable[tuple[Wire, Wire]] | None = None,
    ) -> "Module": ...
    @staticmethod
    def combinatorial(
        assign: Iterable[Term],
        obs: Iterable[tuple[Wire, Wire]] | None = None,
        extl: Iterable[tuple[Wire, Wire]] | None = None,
        intf: Iterable[tuple[Wire, Wire]] | None = None,
    ) -> "Module": ...
    @staticmethod
    def parallel(*modules: "Module") -> "Module": ...
    @property
    def intf(self) -> list[tuple[Wire, Wire]]: ...
    @property
    def extl(self) -> list[tuple[Wire, Wire]]: ...
    @property
    def prvt(self) -> list[tuple[Wire, Wire]]: ...
    @property
    def ctrl(self) -> list[tuple[Wire, Wire]]: ...
    def try_to(self, theory: str) -> object: ...
