/-
Copyright (c) 2024. All rights reserved.
Released under Apache 2.0 license.
Authors: Your Name

Core types and data structures for the AI tactic system.
-/

namespace LeanAI

/-- Configuration for the AI tactic backend -/
structure Config where
  /-- Backend to use: local (Ollama), api (Claude), or hybrid -/
  backend : String := "ollama"
  /-- Model name to use (e.g., "llemma:34b", "claude-sonnet-4.5") -/
  model : String := "llemma:34b"
  /-- Maximum number of retry attempts -/
  maxAttempts : Nat := 3
  /-- Timeout in seconds for LLM calls -/
  timeout : Nat := 30
  /-- Whether to show verbose output -/
  verbose : Bool := false
  /-- Automatically replace ai_solve with generated tactics -/
  autoReplace : Bool := true
  deriving Repr

/-- Result type for LLM operations -/
inductive Result (α : Type) where
  | success : α → Result α
  | failure : String → Result α
  deriving Repr

namespace Result

def isSuccess {α : Type _} : Result α → Bool
  | success _ => true
  | failure _ => false

def map {α β : Type _} (f : α → β) : Result α → Result β
  | success a => success (f a)
  | failure msg => failure msg

def bind {α β : Type _} (f : α → Result β) : Result α → Result β
  | success a => f a
  | failure msg => failure msg

end Result

/-- Represents a proof attempt from the LLM -/
structure ProofAttempt where
  /-- The tactic code generated by the LLM -/
  tactics : String
  /-- Which backend generated this -/
  backend : String
  /-- Attempt number (for retry tracking) -/
  attemptNum : Nat
  deriving Repr

/-- Represents an error that occurred during proof generation -/
structure ProofError where
  /-- The error message -/
  message : String
  /-- The attempt that failed -/
  attempt : Option ProofAttempt
  /-- Error type classification -/
  errorType : String  -- "network", "tactic", "timeout", "config"
  deriving Repr

end LeanAI
