
 name = "Counter"
 version = "0.1.0"
 defaultTargets = ["Counter"]

 [[lean_lib]]
 name = "Core"

 [[lean_lib]]
 name = "LeanAI"

 [[lean_lib]]
 name = "Certificate"

 [[lean_lib]]
 name = "Counter"

 [[require]]
 name = "cslib"
 scope = "leanprover"
 rev = "v4.28.0"

 [[require]]
 name = "smt"
 git = "https://github.com/ufmg-smite/lean-smt.git"
 rev = "main"

#[[require]]
#name = "mylib"
#git = "https://github.com/zeroth/proof-prototyping"
#rev = "main"
