name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

# TODO: at the moment, we skip the `torch` crate due to python2 linking issues
jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      #      - name: Install libpython development headers
      #        run: |
      #          sudo apt-get update
      #          sudo apt-get install -y libpython-dev
      #      - name: Install Poetry
      #        run: |
      #          pipx install poetry
      #          poetry --version
      #      - name: Install Python dependencies with Poetry
      #        working-directory: torch
      #        run: |
      #          poetry config virtualenvs.in-project true
      #          poetry install --no-interaction --no-ansi
      #          VENV_PATH="$(poetry env info --path)"
      #          echo "VIRTUAL_ENV=${VENV_PATH}" >> $GITHUB_ENV
      #          echo "${VENV_PATH}/bin" >> $GITHUB_PATH
      #
      #          echo "PYO3_PYTHON=/usr/bin/python3" >> $GITHUB_ENV
      #          echo "PYO3_USE_ABI3=0" >> $GITHUB_ENV
      - name: Build
        run: cargo build --all-targets --all-features --verbose
      - name: Run tests
        run: cargo test --all-targets --all-features --verbose
      - name: Run doctests
        run: cargo test --all-features --doc --verbose
